@ECHO OFF
:: This file can now be deleted!
:: It was used when setting up the package solution (using https://github.com/LottePitcher/opinionated-package-starter)

:: set up git
git init
git branch -M main
git remote add origin https://github.com/GITHUB_USERNAME/GITHUB_REPOSITORY.git

:: ensure latest Umbraco v17 templates used
dotnet new install Umbraco.Templates@17.* --force

:: use the umbraco-extension dotnet template to add the package project
cd src
dotnet new umbraco-extension -n "PackageStarter" --site-domain "https://localhost:44300" --include-example

:: replace package .csproj with the one from the template so has the extra information needed for publishing to nuget
cd PackageStarter
del PackageStarter.csproj
ren PackageStarter_nuget.csproj PackageStarter.csproj

:: remove the Directory.Packages.props generated by the umbraco-extension template - versions are managed centrally in src/Directory.Packages.props
del Directory.Packages.props

:: add project to solution
cd..
dotnet sln add "PackageStarter"

:: add reference to project from test site
dotnet add "PackageStarter.TestSite/PackageStarter.TestSite.csproj" reference "PackageStarter/PackageStarter.csproj"
